version: "3.8"

services:

  mysql:
    image: rslane/database
    container_name: "running_database"
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: movies


  webserver:
    image: rslane/webserver555
    container_name: "running_front"
    ports:
      - "99:80"
    restart: on-failure

  api:
    image: rslane/api9
    container_name: "running_api"
    restart: on-failure
    ports:
      - "3333:3333"
